spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:${CONFIGURATION_SERVICE_URL:http://localhost:8888}
  cloud:
    config:
      enabled: true
      uri: ${CONFIGURATION_SERVICE_URL:http://localhost:8888}
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6